name: "Tests"

on:
  push:

jobs:
  tests-python-versions:
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          pipx install poetry
          poetry env use ${{ matrix.python }}
          poetry install --with dev
      - name: Run tests
        run: poetry run pytest -vv
